#!/usr/bin/env node

// Small script to seed postgres with fixtures

var
		env = process.env.NODE_ENV || 'dev'
	, config = require('../database')
	, Bookshelf = require('bookshelf')
	, DB = Bookshelf.PG || Bookshelf.initialize({
			client: 'pg',
			connection: config
		})
	,	users = require('../seed/pg/users')
	, User = require('../lib/models/user');

var Users = DB.Collection.extend({
  model: User
});

Users.forge(users).invokeThen('save').then(function (err) {
	process.exit(0);
});
