#!/usr/bin/env node

// Small script to seed postgres with fixtures

var DB = require('../lib/helpers/db')
	,	users = require('../seed/pg/users')
	, User = require('../lib/models/user');

var Users = DB.Collection.extend({
  model: User
});

Users.forge(users).invokeThen('save').then(function (err) {
  console.log(err.message);
	process.exit(0);
});
