#!/usr/bin/env node

// Small script to seed postgres with fixtures

var Bookshelf = require('bookshelf')
  , env = process.env.NODE_ENV || 'dev'
  , config = require('../database')[env]
  , users = require('../seed/pg/users')
  , DB = Bookshelf.initialize({
    client: 'pg',
    connection: config
  });

var User = DB.Model.extend({
  tableName: 'users'
});

var Users = DB.Collection.extend({
  model: User
});

Users.forge(users).invokeThen('save').then(function (err) {
	process.exit(0);
});
