#!/usr/bin/env sh

# This file is meant to be executed inside the Vagrant development VM

# Prevent dpkg-reconfigure interactive sessions
export DEBIAN_FRONTEND=noninteractive


### BEGIN SAMPLE PCAP SERVER ###
apt-get update
apt-get install -y apache2 libpcap-dev tshark
curl -s 'http://www.snaketrap.co.uk/pcaps/Ncapture.pcap' -o /var/www/html/napenthes.pcap
curl -s 'http://malware-traffic-analysis.net/2013/06/18/2013-06-18.pcap' -o /var/www/html/java.pcap
### END SAMPLE PCAP SERVER ###


### BEGIN OPENLDAP ###
# slapd doesn't seem to work right unless you configure it via debconf
# The password for all users is opensoc
debconf-set-selections /vagrant/seed/slapd.seed
apt-get update
apt-get -y install slapd ldap-utils

cd /vagrant/seed/ldap
ldapmodify -Y EXTERNAL -H ldapi:/// -f logging.ldif
ldapmodify -Y EXTERNAL -H ldapi:/// -f config.ldif
ldapadd -D cn=admin,cn=config -w "opensoc" -H ldapi:/// -f memberof_add.ldif
ldapadd -D cn=admin,cn=config -w "opensoc" -H ldapi:/// -f memberof_config.ldif
cd -
### END OPENLDAP ###


### BEGIN REDIS ###
apt-get -y install redis-server
update-rc.d redis-server defaults 95 10
sed -i '/bind 127.0.0.1/c\bind 0.0.0.0' /etc/redis/redis.conf
service redis-server restart
### END REDIS ###


### BEGIN ELASTICSEARCH ###
apt-get -y install openjdk-7-jre-headless
wget --quiet https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.1.1.deb
dpkg -i elasticsearch-1.1.1.deb
rm -rf elasticsearch-1.1.1.deb
cd /usr/share/elasticsearch
bin/plugin -install mobz/elasticsearch-head
cd -
update-rc.d elasticsearch defaults 95 10
service elasticsearch restart
### END ELASTICSEARCH ###


### NODE SETUP ###
apt-get update
apt-get install -y nodejs npm

ln -s /usr/bin/nodejs /usr/bin/node
npm install -g nodemon

cd /vagrant
rm -rf node_modules
su vagrant -c "npm install"
su vagrant -c  "echo 'export NODE_ENV=vagrant' >> /home/vagrant/.bashrc"
su vagrant -c "ln -s /vagrant/.nodemonignore ~/.nodemonignore"
cd -
### END NODE SETUP ###
